[provider]
image = "node"

[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc", "gnumake", "pkg-config"]

[phases.dependencies]
cmds = [
  "npm install --build-from-source --prefer-offline"
]

[start]
cmd = "next start"
